//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PopAppShops.Console.PlayersService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="https://my-game.azurewebsites.net", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categories", Namespace="https://my-game.azurewebsites.net")]
    [System.SerializableAttribute()]
    public partial class Categories : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://my-game.azurewebsites.net", ConfigurationName="PlayersService.PlayersSoap")]
    public interface PlayersSoap {
        
        // CODEGEN: Generating message contract since element name GetCategoryResult from namespace https://my-game.azurewebsites.net is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://my-game.azurewebsites.net/GetCategory", ReplyAction="*")]
        PopAppShops.Console.PlayersService.GetCategoryResponse GetCategory(PopAppShops.Console.PlayersService.GetCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://my-game.azurewebsites.net/GetCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<PopAppShops.Console.PlayersService.GetCategoryResponse> GetCategoryAsync(PopAppShops.Console.PlayersService.GetCategoryRequest request);
        
        // CODEGEN: Generating message contract since element name payload from namespace https://my-game.azurewebsites.net is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://my-game.azurewebsites.net/Create", ReplyAction="*")]
        PopAppShops.Console.PlayersService.CreateResponse Create(PopAppShops.Console.PlayersService.CreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://my-game.azurewebsites.net/Create", ReplyAction="*")]
        System.Threading.Tasks.Task<PopAppShops.Console.PlayersService.CreateResponse> CreateAsync(PopAppShops.Console.PlayersService.CreateRequest request);
        
        // CODEGEN: Generating message contract since element name GetConfigResult from namespace https://my-game.azurewebsites.net is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://my-game.azurewebsites.net/GetConfig", ReplyAction="*")]
        PopAppShops.Console.PlayersService.GetConfigResponse GetConfig(PopAppShops.Console.PlayersService.GetConfigRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://my-game.azurewebsites.net/GetConfig", ReplyAction="*")]
        System.Threading.Tasks.Task<PopAppShops.Console.PlayersService.GetConfigResponse> GetConfigAsync(PopAppShops.Console.PlayersService.GetConfigRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCategory", Namespace="https://my-game.azurewebsites.net", Order=0)]
        public PopAppShops.Console.PlayersService.GetCategoryRequestBody Body;
        
        public GetCategoryRequest() {
        }
        
        public GetCategoryRequest(PopAppShops.Console.PlayersService.GetCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCategoryRequestBody {
        
        public GetCategoryRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCategoryResponse", Namespace="https://my-game.azurewebsites.net", Order=0)]
        public PopAppShops.Console.PlayersService.GetCategoryResponseBody Body;
        
        public GetCategoryResponse() {
        }
        
        public GetCategoryResponse(PopAppShops.Console.PlayersService.GetCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://my-game.azurewebsites.net")]
    public partial class GetCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PopAppShops.Console.PlayersService.ArrayOfString GetCategoryResult;
        
        public GetCategoryResponseBody() {
        }
        
        public GetCategoryResponseBody(PopAppShops.Console.PlayersService.ArrayOfString GetCategoryResult) {
            this.GetCategoryResult = GetCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Create", Namespace="https://my-game.azurewebsites.net", Order=0)]
        public PopAppShops.Console.PlayersService.CreateRequestBody Body;
        
        public CreateRequest() {
        }
        
        public CreateRequest(PopAppShops.Console.PlayersService.CreateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://my-game.azurewebsites.net")]
    public partial class CreateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PopAppShops.Console.PlayersService.Categories payload;
        
        public CreateRequestBody() {
        }
        
        public CreateRequestBody(PopAppShops.Console.PlayersService.Categories payload) {
            this.payload = payload;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateResponse", Namespace="https://my-game.azurewebsites.net", Order=0)]
        public PopAppShops.Console.PlayersService.CreateResponseBody Body;
        
        public CreateResponse() {
        }
        
        public CreateResponse(PopAppShops.Console.PlayersService.CreateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://my-game.azurewebsites.net")]
    public partial class CreateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateResult;
        
        public CreateResponseBody() {
        }
        
        public CreateResponseBody(string CreateResult) {
            this.CreateResult = CreateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetConfigRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetConfig", Namespace="https://my-game.azurewebsites.net", Order=0)]
        public PopAppShops.Console.PlayersService.GetConfigRequestBody Body;
        
        public GetConfigRequest() {
        }
        
        public GetConfigRequest(PopAppShops.Console.PlayersService.GetConfigRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetConfigRequestBody {
        
        public GetConfigRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetConfigResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetConfigResponse", Namespace="https://my-game.azurewebsites.net", Order=0)]
        public PopAppShops.Console.PlayersService.GetConfigResponseBody Body;
        
        public GetConfigResponse() {
        }
        
        public GetConfigResponse(PopAppShops.Console.PlayersService.GetConfigResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://my-game.azurewebsites.net")]
    public partial class GetConfigResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetConfigResult;
        
        public GetConfigResponseBody() {
        }
        
        public GetConfigResponseBody(string GetConfigResult) {
            this.GetConfigResult = GetConfigResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PlayersSoapChannel : PopAppShops.Console.PlayersService.PlayersSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlayersSoapClient : System.ServiceModel.ClientBase<PopAppShops.Console.PlayersService.PlayersSoap>, PopAppShops.Console.PlayersService.PlayersSoap {
        
        public PlayersSoapClient() {
        }
        
        public PlayersSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlayersSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayersSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayersSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PopAppShops.Console.PlayersService.GetCategoryResponse PopAppShops.Console.PlayersService.PlayersSoap.GetCategory(PopAppShops.Console.PlayersService.GetCategoryRequest request) {
            return base.Channel.GetCategory(request);
        }
        
        public PopAppShops.Console.PlayersService.ArrayOfString GetCategory() {
            PopAppShops.Console.PlayersService.GetCategoryRequest inValue = new PopAppShops.Console.PlayersService.GetCategoryRequest();
            inValue.Body = new PopAppShops.Console.PlayersService.GetCategoryRequestBody();
            PopAppShops.Console.PlayersService.GetCategoryResponse retVal = ((PopAppShops.Console.PlayersService.PlayersSoap)(this)).GetCategory(inValue);
            return retVal.Body.GetCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PopAppShops.Console.PlayersService.GetCategoryResponse> PopAppShops.Console.PlayersService.PlayersSoap.GetCategoryAsync(PopAppShops.Console.PlayersService.GetCategoryRequest request) {
            return base.Channel.GetCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<PopAppShops.Console.PlayersService.GetCategoryResponse> GetCategoryAsync() {
            PopAppShops.Console.PlayersService.GetCategoryRequest inValue = new PopAppShops.Console.PlayersService.GetCategoryRequest();
            inValue.Body = new PopAppShops.Console.PlayersService.GetCategoryRequestBody();
            return ((PopAppShops.Console.PlayersService.PlayersSoap)(this)).GetCategoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PopAppShops.Console.PlayersService.CreateResponse PopAppShops.Console.PlayersService.PlayersSoap.Create(PopAppShops.Console.PlayersService.CreateRequest request) {
            return base.Channel.Create(request);
        }
        
        public string Create(PopAppShops.Console.PlayersService.Categories payload) {
            PopAppShops.Console.PlayersService.CreateRequest inValue = new PopAppShops.Console.PlayersService.CreateRequest();
            inValue.Body = new PopAppShops.Console.PlayersService.CreateRequestBody();
            inValue.Body.payload = payload;
            PopAppShops.Console.PlayersService.CreateResponse retVal = ((PopAppShops.Console.PlayersService.PlayersSoap)(this)).Create(inValue);
            return retVal.Body.CreateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PopAppShops.Console.PlayersService.CreateResponse> PopAppShops.Console.PlayersService.PlayersSoap.CreateAsync(PopAppShops.Console.PlayersService.CreateRequest request) {
            return base.Channel.CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<PopAppShops.Console.PlayersService.CreateResponse> CreateAsync(PopAppShops.Console.PlayersService.Categories payload) {
            PopAppShops.Console.PlayersService.CreateRequest inValue = new PopAppShops.Console.PlayersService.CreateRequest();
            inValue.Body = new PopAppShops.Console.PlayersService.CreateRequestBody();
            inValue.Body.payload = payload;
            return ((PopAppShops.Console.PlayersService.PlayersSoap)(this)).CreateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PopAppShops.Console.PlayersService.GetConfigResponse PopAppShops.Console.PlayersService.PlayersSoap.GetConfig(PopAppShops.Console.PlayersService.GetConfigRequest request) {
            return base.Channel.GetConfig(request);
        }
        
        public string GetConfig() {
            PopAppShops.Console.PlayersService.GetConfigRequest inValue = new PopAppShops.Console.PlayersService.GetConfigRequest();
            inValue.Body = new PopAppShops.Console.PlayersService.GetConfigRequestBody();
            PopAppShops.Console.PlayersService.GetConfigResponse retVal = ((PopAppShops.Console.PlayersService.PlayersSoap)(this)).GetConfig(inValue);
            return retVal.Body.GetConfigResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PopAppShops.Console.PlayersService.GetConfigResponse> PopAppShops.Console.PlayersService.PlayersSoap.GetConfigAsync(PopAppShops.Console.PlayersService.GetConfigRequest request) {
            return base.Channel.GetConfigAsync(request);
        }
        
        public System.Threading.Tasks.Task<PopAppShops.Console.PlayersService.GetConfigResponse> GetConfigAsync() {
            PopAppShops.Console.PlayersService.GetConfigRequest inValue = new PopAppShops.Console.PlayersService.GetConfigRequest();
            inValue.Body = new PopAppShops.Console.PlayersService.GetConfigRequestBody();
            return ((PopAppShops.Console.PlayersService.PlayersSoap)(this)).GetConfigAsync(inValue);
        }
    }
}
